export const FETCH_STATS_ERROR = 'FETCH_STATS_ERROR';
export const FETCH_STATS_BY_TYPE_SUCCESS = 'FETCH_STATS_BY_TYPE_SUCCESS';
export const FETCH_STATS_LOADING = 'FETCH_STATS_LOADING';

export const UPLOAD_FILES_LOADING = 'UPLOAD_FILES_LOADING';
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS';
export const UPLOAD_FILES_ERROR = 'UPLOAD_FILES_ERROR';

export const FETCH_LIST_FILES_LOADING = 'FETCH_LIST_FILES_LOADING';
export const FETCH_LIST_FILES_SUCCESS = 'FETCH_LIST_FILES';
export const FETCH_LIST_FILES_ERROR = 'FETCH_LIST_FILES_ERROR';

export const DELETE_FILE_LOADING = 'DELETE_FILE_LOADING';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_ERROR = 'DELETE_FILE_ERROR';

export const INSERT_FOLDER_LOADING = 'INSERT_FOLDER_LOADING';
export const INSERT_FOLDER_SUCCESS = 'INSERT_FOLDER_SUCCESS';
export const INSERT_FOLDER_ERROR = 'INSERT_FOLDER_ERROR';

export const UPDATE_FOLDER_LOADING = 'UPDATE_FOLDER_LOADING';
export const UPDATE_FOLDER_SUCCESS = 'UPDATE_FOLDER_SUCCESS';
export const UPDATE_FOLDER_ERROR = 'UPDATE_FOLDER_ERROR';

export const FETCH_FOLDER_LOADING = 'FETCH_FOLDER_LOADING';
export const FETCH_FOLDER_SUCCESS = 'FETCH_FOLDER_SUCCESS';
export const FETCH_FOLDER_ERROR = 'FETCH_FOLDER_ERROR';

export const DELETE_FOLDER_LOADING = 'DELETE_FOLDER_LOADING';
export const DELETE_FOLDER_SUCCESS = 'DELETE_FOLDER_SUCCESS';
export const DELETE_FOLDER_ERROR = 'DELETE_FOLDER_ERROR';

export const UPDATE_FILE_LOADING = 'UPDATE_FILE_LOADING';
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS';
export const UPDATE_FILE_ERROR = 'UPDATE_FILE_ERROR';

export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
